package com.erudit.notification.repository;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import java.sql.Timestamp;import java.time.*;import java.util.*;
@Repository public class NotificationTriggerRepository {
 public record Target(UUID userId,Map<String,String> parameters,String key,ZoneId zone){}
 private final JdbcTemplate jdbc;public NotificationTriggerRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public List<Target> inactive(Instant now){return jdbc.query("SELECT id,created_at FROM users WHERE status='ACTIVE' AND created_at<=?",(r,n)->{Instant created=r.getTimestamp("created_at").toInstant();long days=Duration.between(created,now).toDays();return new Target(r.getObject("id",UUID.class),Map.of("days",Long.toString(days),"level",days>=7?"MOTIVATING":"SOFT"),"inactivity:"+(days>=7?"7+":"3"),ZoneId.of("UTC"));},Timestamp.from(now.minus(Duration.ofDays(3))));}
 public List<Target> dailyQuiz(Instant now){return jdbc.query("SELECT u.id,COALESCE(s.time_zone,'UTC') zone FROM users u LEFT JOIN user_settings s ON s.user_id=u.id WHERE u.status='ACTIVE'",(r,n)->{ZoneId zone;try{zone=ZoneId.of(r.getString("zone"));}catch(Exception e){zone=ZoneId.of("UTC");}return new Target(r.getObject("id",UUID.class),Map.of(),"daily-quiz:"+now.atZone(zone).toLocalDate(),zone);}).stream().filter(t->now.atZone(t.zone()).getHour()==9).toList();}
 public List<Target> newContent(Instant since){return jdbc.query("SELECT DISTINCT f.user_id,c.id,c.title,COALESCE(s.time_zone,'UTC') zone FROM user_favorite_categories f JOIN content c ON c.category_id=f.category_id LEFT JOIN user_settings s ON s.user_id=f.user_id WHERE c.status='PUBLISHED' AND c.created_at>=?",(r,n)->new Target(r.getObject("user_id",UUID.class),Map.of("title",r.getString("title")),"content:"+r.getObject("id",UUID.class),zone(r.getString("zone"))),Timestamp.from(since));}
 public List<Target> achievements(){return jdbc.query("SELECT p.user_id,p.points,COALESCE(s.time_zone,'UTC') zone FROM user_rating_profiles p JOIN users u ON u.id::text=p.user_id LEFT JOIN user_settings s ON s.user_id=u.id WHERE p.points>=100",(r,n)->{long milestone=(r.getLong("points")/100)*100;return new Target(UUID.fromString(r.getString("user_id")),Map.of("points",Long.toString(milestone)),"achievement:"+milestone,zone(r.getString("zone")));});}
 public List<Target> subscriptions(Instant now){return jdbc.query("SELECT DISTINCT s.user_id,s.end_date,COALESCE(us.time_zone,'UTC') zone FROM subscriptions s LEFT JOIN user_settings us ON us.user_id=s.user_id WHERE s.status='ACTIVE' AND s.end_date>? AND s.end_date<=?",(r,n)->new Target(r.getObject("user_id",UUID.class),Map.of("expiresAt",r.getTimestamp("end_date").toInstant().toString()),"subscription:"+r.getTimestamp("end_date").toInstant(),zone(r.getString("zone"))),Timestamp.from(now),Timestamp.from(now.plus(Duration.ofDays(3))));}
 private static ZoneId zone(String value){try{return ZoneId.of(value);}catch(Exception e){return ZoneId.of("UTC");}}
}
