spring:
  application:
    name: erudit
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/erudit}
    username: ${DB_USERNAME:erudit}
    password: ${DB_PASSWORD:erudit}
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}

clickhouse:
  url: ${CLICKHOUSE_URL:jdbc:clickhouse:http://localhost:8123/erudit}
  username: ${CLICKHOUSE_USERNAME:erudit}
  password: ${CLICKHOUSE_PASSWORD:erudit}

springdoc:
  swagger-ui:
    url: /openapi.yaml
    tags-sorter: alpha
    operations-sorter: alpha
    try-it-out-enabled: true
