package com.erudit.admin.repository;

import com.erudit.admin.dto.AdminAuditPage;
import com.erudit.admin.model.AdminAuditRecord;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import java.sql.*;import java.time.*;import java.util.*;
@Repository public class AdminAuditRepository {
 private final JdbcTemplate jdbc;private final ObjectMapper json=new ObjectMapper();public AdminAuditRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public void record(String actor,String action,String targetType,String targetId,Map<String,Object> metadata,Instant at){try{jdbc.update("INSERT INTO admin_audit_log(id,actor_id,action,target_type,target_id,occurred_at,metadata) VALUES(?,?,?,?,?,?,?)",UUID.randomUUID(),actor,action,targetType,targetId,Timestamp.from(at),json.writeValueAsString(metadata));}catch(Exception e){throw new IllegalStateException(e);}}
 public AdminAuditPage list(int page,int size,UUID actor,String action,Instant from,Instant to){String where=" WHERE (? IS NULL OR actor_id=?) AND (? IS NULL OR action=?) AND (? IS NULL OR occurred_at>=?) AND (? IS NULL OR occurred_at<=?)";Object[] filter={actor==null?null:actor.toString(),actor==null?null:actor.toString(),action,action,from==null?null:Timestamp.from(from),from==null?null:Timestamp.from(from),to==null?null:Timestamp.from(to),to==null?null:Timestamp.from(to)};var args=new ArrayList<Object>(Arrays.asList(filter));args.add(size);args.add(page*size);var rows=jdbc.query("SELECT * FROM admin_audit_log"+where+" ORDER BY occurred_at DESC,id DESC LIMIT ? OFFSET ?",(rs,n)->map(rs),args.toArray());long total=jdbc.queryForObject("SELECT count(*) FROM admin_audit_log"+where,Long.class,filter);return new AdminAuditPage(rows,total,page,size);}
 private AdminAuditRecord map(ResultSet r)throws SQLException{try{return new AdminAuditRecord(r.getObject("id",UUID.class),r.getString("actor_id"),r.getString("action"),r.getString("target_type"),r.getString("target_id"),r.getTimestamp("occurred_at").toInstant(),json.readValue(r.getString("metadata"),new TypeReference<>(){}));}catch(Exception e){throw new SQLException(e);}}
}
