package com.erudit.admin;
import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.MockMvc;import org.springframework.transaction.annotation.Transactional;import java.sql.Timestamp;import java.time.*;import java.util.UUID;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Transactional class AdminIntegrationTest {
 @Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;
 @Test void adminListsBlocksNotifiesAndReadsAudit()throws Exception{UUID admin=create("admin","ADMIN"),target=create("target","USER"),template=UUID.randomUUID();jdbc.update("INSERT INTO notification_templates(id,notification_type,channel,title,body,updated_at) VALUES(?,'SOCIAL','EMAIL','Admin','Message',?)",template,Timestamp.from(Instant.now()));jdbc.update("INSERT INTO notification_preferences(user_id,updated_at) VALUES(?,?)",target,Timestamp.from(Instant.now()));jdbc.update("INSERT INTO notification_preference_channels VALUES(?,'EMAIL')",target);jdbc.update("INSERT INTO notification_preference_types VALUES(?,'SOCIAL')",target);
  mvc.perform(get("/api/v1/admin/users").with(user(admin.toString()).roles("ADMIN"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(org.hamcrest.Matchers.greaterThanOrEqualTo(2)));
  mvc.perform(post("/api/v1/admin/users/{id}/block",target).with(user(admin.toString()).roles("ADMIN"))).andExpect(status().isNoContent());
  mvc.perform(post("/api/v1/admin/notifications/send-many").with(user(admin.toString()).roles("ADMIN")).contentType(MediaType.APPLICATION_JSON).content("{\"userIds\":[\""+target+"\"],\"templateId\":\""+template+"\",\"parameters\":{}}" )).andExpect(status().isOk()).andExpect(jsonPath("$.data.count").value(1));
  mvc.perform(get("/api/v1/admin/audit").param("actorId",admin.toString()).with(user(admin.toString()).roles("ADMIN"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(2)).andExpect(jsonPath("$.data[0].metadata.result").value("SUCCESS"));
  mvc.perform(get("/api/v1/admin/users").with(user(target.toString()).roles("USER"))).andExpect(status().isForbidden());
 }
 private UUID create(String name,String role){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO users(id,email,password_hash,name,created_at,status,role,email_verified) VALUES(?,?,?,?,?,'ACTIVE',?,true)",id,name+id+"@test.local","hash",name,java.time.LocalDateTime.now(),role);return id;}
}
